### ISSUE TITLE
in contact info page on message section anyone can enter number in name input-field [BUG]

### ISSUE THREAD

**Issue by anish013326** [amitpatle/Portfolio-Site#4]
## To prevent users from entering numbers in the name input field on your contact info page, you can add some validation

![image](https://github.com/user-attachments/assets/1e9fc9fd-6b82-4c86-b2e7-bf9350f298c4)

**Comment by amitpatle** [comment]
I appreciate your efforts @anish013326 . I'll try to address any issue you brought up as soon as I can.

**Comment by anish013326** [comment]
Thank you for the appreciation! It sounds like you're on track to make great progress. If you need any assistance with specific topics or projects, feel free to reach out, and I'll be here to collaborate

**Comment by amitpatle** [comment]
![Screenshot 2024-10-31 162548](https://github.com/user-attachments/assets/a2e2d964-3264-4526-bb2b-915df33e678c)

fixed
